name: deploy to lambda
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
jobs:
  deploy_source:
    name: deploy lambda from source
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v1
        
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
        
      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-west-2'
          
      - name: Deploy
        run: |
          # Create S3 Bucket to store code
          aws s3api head-bucket --bucket "phoebedev" 2>/dev/null \
            || aws s3 mb s3://phoebedev

          # Run SAM Deploy
          sam deploy --template-file phoebedev.yaml --stack-name phoebedev --s3-bucket phoebedev --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM
